### ISSUE TITLE
Change Instructions 

### ISSUE THREAD

**Issue by jatv93** [breatheco-de/exercise-instagram-feed#17]
Put this in How to start this project:

Go to Start New Project, then click on New Empty. 

![image](https://user-images.githubusercontent.com/48845580/117697277-4b336b00-b190-11eb-8f9b-7da6b519eabb.png)

The Spanish instructions need an update

@ElviraQDP

**Comment by ElviraQDP** [comment]
this needs to be pushed: https://github.com/breatheco-de/exercise-instagram-feed/pull/14
to solve the issue @alesanchezr @mortegac

**Comment by ElviraQDP** [comment]
resuelto!
